In [1]:
import polars as pl
from pathlib import Path

In [2]:
data = pl.read_parquet("data/raw/20250811_bgg.parquet")

In [5]:
data.columns

['id',
 'thumbnail_url',
 'image_url',
 'description',
 'publication_year',
 'min_players',
 'max_players',
 'playing_time',
 'min_playing_time',
 'max_playing_time',
 'min_age',
 'mechanics',
 'categories',
 'name',
 'num_ratings',
 'avg_rating',
 'bayesian_avg_rating',
 'stddev_rating',
 'owned_by',
 'wanted_by',
 'wished_by']

id -> will just be the index, the key
thumbnail_url & image_url -> won't be used
description will be vectorized, so, is not needed atm
publication_year -> can be used as weight to get games similar regarding the release date
min + max players -> we cna probably make a new column from this.
playing_time + min + max -> we can probably make a new column from this.
min_age -> probably better kept as a feature.
mechanics + categories -> will be hot encoded.
name -> not needed.
num_rates + avg rating -> will probably not be used.
bayesian_avg_rating -> will be used as a weight

owned + wanted + wished -> we can probably build something realted to this.

In [ ]:
weights:
-> publication_year
-> playing_time
-> bayesian_avg_rating 
-> popularity score
-> distance

In [12]:
import polars as pl
data = pl.read_parquet("data/processed/20251217_bgg.parquet")

In [13]:
data

shape: (72_629, 177)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id     ┆ thumbnail_ ┆ image_url  ┆ descripti ┆ … ┆ mechanics ┆ mechanics ┆ mechanics ┆ mechanics │
│ ---    ┆ url        ┆ ---        ┆ on        ┆   ┆ _Victory  ┆ _Voting   ┆ _Worker   ┆ _Zone of  │
│ str    ┆ ---        ┆ str        ┆ ---       ┆   ┆ Points as ┆ ---       ┆ Placement ┆ Control   │
│        ┆ str        ┆            ┆ str       ┆   ┆ a …       ┆ i64       ┆ ---       ┆ ---       │
│        ┆            ┆            ┆           ┆   ┆ ---       ┆           ┆ i64       ┆ i64       │
│        ┆            ┆            ┆           ┆   ┆ i64       ┆           ┆           ┆           │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1      ┆ https://cf ┆ https://cf ┆ Die       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│        ┆ .geekdo-im ┆ .geekdo-im ┆ Macher is ┆   ┆           ┆           ┆           ┆           │
│        ┆ ages.com/r ┆ ages.com/r ┆ a game    ┆   ┆           ┆           ┆           ┆           │
│        ┆ …          ┆ …          ┆ about     ┆   ┆           ┆           ┆           ┆           │
│        ┆            ┆            ┆ sev…      ┆   ┆           ┆           ┆           ┆           │
│ 2      ┆ https://cf ┆ https://cf ┆ Dragonmas ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│        ┆ .geekdo-im ┆ .geekdo-im ┆ ter is a  ┆   ┆           ┆           ┆           ┆           │
│        ┆ ages.com/o ┆ ages.com/o ┆ trick-tak ┆   ┆           ┆           ┆           ┆           │
│        ┆ …          ┆ …          ┆ ing…      ┆   ┆           ┆           ┆           ┆           │
│ 3      ┆ https://cf ┆ https://cf ┆ Samurai   ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│        ┆ .geekdo-im ┆ .geekdo-im ┆ is set in ┆   ┆           ┆           ┆           ┆           │
│        ┆ ages.com/o ┆ ages.com/o ┆ medieval  ┆   ┆           ┆           ┆           ┆           │
│        ┆ …          ┆ …          ┆ Jap…      ┆   ┆           ┆           ┆           ┆           │
│ 4      ┆ https://cf ┆ https://cf ┆ When you  ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│        ┆ .geekdo-im ┆ .geekdo-im ┆ see the   ┆   ┆           ┆           ┆           ┆           │
│        ┆ ages.com/n ┆ ages.com/n ┆ triangula ┆   ┆           ┆           ┆           ┆           │
│        ┆ …          ┆ …          ┆ r bo…     ┆   ┆           ┆           ┆           ┆           │
│ 5      ┆ https://cf ┆ https://cf ┆ In        ┆ … ┆ 1         ┆ 0         ┆ 0         ┆ 0         │
│        ┆ .geekdo-im ┆ .geekdo-im ┆ Acquire,  ┆   ┆           ┆           ┆           ┆           │
│        ┆ ages.com/g ┆ ages.com/g ┆ each      ┆   ┆           ┆           ┆           ┆           │
│        ┆ …          ┆ …          ┆ player    ┆   ┆           ┆           ┆           ┆           │
│        ┆            ┆            ┆ strate…   ┆   ┆           ┆           ┆           ┆           │
│ …      ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 285655 ┆ https://cf ┆ https://cf ┆ Powerful  ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│        ┆ .geekdo-im ┆ .geekdo-im ┆ warriors  ┆   ┆           ┆           ┆           ┆           │
│        ┆ ages.com/W ┆ ages.com/W ┆ face      ┆   ┆           ┆           ┆           ┆           │
│        ┆ …          ┆ …          ┆ death t…  ┆   ┆           ┆           ┆           ┆           │
│ 285700 ┆ https://cf ┆ https://cf ┆ Mathemati ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│        ┆ .geekdo-im ┆ .geekdo-im ┆ c-roll is ┆   ┆           ┆           ┆           ┆           │
│        ┆ ages.com/a ┆ ages.com/a ┆ a roll    ┆   ┆           ┆           ┆           ┆           │
│        ┆ …          ┆ …          ┆ &amp…     ┆   ┆           ┆           ┆           ┆           │
│ 285703 ┆ https://cf ┆ https://cf ┆ The       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│        ┆ .geekdo-im ┆ .geekdo-im ┆ capital   ┆   ┆           ┆           ┆           ┆           │
│        ┆ ages.com/w ┆ ages.com/w ┆ is abuzz  ┆   ┆           ┆           ┆           ┆           │
│        ┆ …          ┆ …          ┆ with      ┆   ┆           ┆           ┆           ┆           │
│        ┆            ┆            ┆ stra…     ┆   ┆           ┆           ┆           ┆           │
│ 285707 ┆ https://cf ┆ https://cf ┆ DUBITO is ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│        ┆ .geekdo-im ┆ .geekdo-im ┆ a dice    ┆   ┆           ┆           ┆           ┆           │
│        ┆ ages.com/U ┆ ages.com/U ┆ game      ┆   ┆           ┆           ┆           ┆           │
│        ┆ …          ┆ …          ┆ based on… ┆   ┆           ┆           ┆           ┆           │
│ 285712 ┆ https://cf ┆ https://cf ┆ Stroll    ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│        ┆ .geekdo-im ┆ .geekdo-im ┆ around    ┆   ┆           ┆           ┆           ┆           │
│        ┆ ages.com/r ┆ ages.com/r ┆ Tan Tan   ┆   ┆           ┆           ┆           ┆           │
│        ┆ …          ┆ …          ┆ Caravan'… ┆   ┆           ┆           ┆           ┆           │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [15]:
data.filter(pl.col("name").str.contains("CATAN", literal=False))

shape: (3, 177)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id     ┆ thumbnail_ ┆ image_url  ┆ descripti ┆ … ┆ mechanics ┆ mechanics ┆ mechanics ┆ mechanics │
│ ---    ┆ url        ┆ ---        ┆ on        ┆   ┆ _Victory  ┆ _Voting   ┆ _Worker   ┆ _Zone of  │
│ str    ┆ ---        ┆ str        ┆ ---       ┆   ┆ Points as ┆ ---       ┆ Placement ┆ Control   │
│        ┆ str        ┆            ┆ str       ┆   ┆ a …       ┆ i64       ┆ ---       ┆ ---       │
│        ┆            ┆            ┆           ┆   ┆ ---       ┆           ┆ i64       ┆ i64       │
│        ┆            ┆            ┆           ┆   ┆ i64       ┆           ┆           ┆           │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 13     ┆ https://cf ┆ https://cf ┆ In CATAN  ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│        ┆ .geekdo-im ┆ .geekdo-im ┆ (formerly ┆   ┆           ┆           ┆           ┆           │
│        ┆ ages.com/P ┆ ages.com/P ┆ The       ┆   ┆           ┆           ┆           ┆           │
│        ┆ …          ┆ …          ┆ Settler…  ┆   ┆           ┆           ┆           ┆           │
│ 17419  ┆ https://cf ┆ https://cf ┆ To commem ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│        ┆ .geekdo-im ┆ .geekdo-im ┆ orate     ┆   ┆           ┆           ┆           ┆           │
│        ┆ ages.com/L ┆ ages.com/L ┆ this      ┆   ┆           ┆           ┆           ┆           │
│        ┆ …          ┆ …          ┆ momentous ┆   ┆           ┆           ┆           ┆           │
│        ┆            ┆            ┆ …         ┆   ┆           ┆           ┆           ┆           │
│ 282853 ┆ https://cf ┆ https://cf ┆ Twenty    ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0         │
│        ┆ .geekdo-im ┆ .geekdo-im ┆ years     ┆   ┆           ┆           ┆           ┆           │
│        ┆ ages.com/r ┆ ages.com/r ┆ ago, the  ┆   ┆           ┆           ┆           ┆           │
│        ┆ …          ┆ …          ┆ settlers… ┆   ┆           ┆           ┆           ┆           │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
to exclude:
thumbnail_url
image_url
description
publication_year
min_playing_time
max_playing_time
playing_time
min_age
name
num_ratings
avg_rating
stddev_rating

In [4]:
data.columns

['id',
 'thumbnail_url',
 'image_url',
 'description',
 'publication_year',
 'playing_time',
 'min_playing_time',
 'max_playing_time',
 'min_age',
 'name',
 'num_ratings',
 'avg_rating',
 'bayesian_avg_rating',
 'stddev_rating',
 'to_recommend',
 'players_1',
 'players_2',
 'players_3',
 'players_4',
 'players_5',
 'players_6',
 'players_7',
 'players_8',
 'players_9',
 'players_10',
 'players_11',
 'players_12',
 'players_13',
 'players_14',
 'players_15',
 'players_16',
 'players_17',
 'players_18',
 'players_19',
 'players_20',
 'popularity_score',
 'categories_Abstract Strategy',
 'categories_Action / Dexterity',
 'categories_Adventure',
 'categories_Ancient',
 'categories_Animals',
 'categories_Bluffing',
 'categories_Book',
 'categories_Card Game',
 "categories_Children's Game",
 'categories_Collectible Components',
 'categories_Comic Book / Strip',
 'categories_Deduction',
 'categories_Dice',
 'categories_Economic',
 'categories_Educational',
 'categories_Exploration',
 'categories_Fantasy',
 'categories_Fighting',
 'categories_Horror',
 'categories_Humor',
 'categories_Math',
 'categories_Medieval',
 'categories_Memory',
 'categories_Miniatures',
 'categories_Modern Warfare',
 'categories_Movies / TV / Radio theme',
 'categories_Murder / Mystery',
 'categories_Nautical',
 'categories_Negotiation',
 'categories_Novel-based',
 'categories_Number',
 'categories_Party Game',
 'categories_Political',
 'categories_Print & Play',
 'categories_Puzzle',
 'categories_Racing',
 'categories_Real-time',
 'categories_Science Fiction',
 'categories_Sports',
 'categories_Territory Building',
 'categories_Transportation',
 'categories_Travel',
 'categories_Trivia',
 'categories_Wargame',
 'categories_Word Game',
 'categories_World War II',
 'mechanics_Acting',
 'mechanics_Action Points',
 'mechanics_Action Queue',
 'mechanics_Area Majority / Influence',
 'mechanics_Area Movement',
 'mechanics_Area-Impulse',
 'mechanics_Auction / Bidding',
 'mechanics_Betting and Bluffing',
 'mechanics_Campaign / Battle Card Driven',
 'mechanics_Card Play Conflict Resolution',
 'mechanics_Chit-Pull System',
 'mechanics_Closed Drafting',
 'mechanics_Commodity Speculation',
 'mechanics_Communication Limits',
 'mechanics_Connections',
 'mechanics_Contracts',
 'mechanics_Cooperative Game',
 'mechanics_Critical Hits and Failures',
 'mechanics_Deck Construction',
 'mechanics_Deck, Bag, and Pool Building',
 'mechanics_Deduction',
 'mechanics_Dice Rolling',
 'mechanics_Die Icon Resolution',
 'mechanics_Enclosure',
 'mechanics_End Game Bonuses',
 'mechanics_Events',
 'mechanics_Flicking',
 'mechanics_Grid Movement',
 'mechanics_Hand Management',
 'mechanics_Hexagon Grid',
 'mechanics_Hidden Movement',
 'mechanics_Hidden Roles',
 'mechanics_Income',
 'mechanics_Ladder Climbing',
 'mechanics_Line Drawing',
 'mechanics_Line of Sight',
 'mechanics_Mancala',
 'mechanics_Market',
 'mechanics_Matching',
 'mechanics_Measurement Movement',
 'mechanics_Memory',
 'mechanics_Modular Board',
 'mechanics_Movement Points',
 'mechanics_Multi-Use Cards',
 'mechanics_Negotiation',
 'mechanics_Network and Route Building',
 'mechanics_Open Drafting',
 'mechanics_Ownership',
 'mechanics_Paper-and-Pencil',
 'mechanics_Pattern Building',
 'mechanics_Pattern Recognition',
 'mechanics_Pick-up and Deliver',
 'mechanics_Player Elimination',
 'mechanics_Point to Point Movement',
 'mechanics_Push Your Luck',
 'mechanics_Race',
 'mechanics_Ratio / Combat Results Table',
 'mechanics_Re-rolling and Locking',
 'mechanics_Real-Time',
 'mechanics_Rock-Paper-Scissors',
 'mechanics_Role Playing',
 'mechanics_Roll / Spin and Move',
 'mechanics_Scenario / Mission / Campaign Game',
 'mechanics_Score-and-Reset Game',
 'mechanics_Secret Unit Deployment',
 'mechanics_Semi-Cooperative Game',
 'mechanics_Set Collection',
 'mechanics_Simulation',
 'mechanics_Simultaneous Action Selection',
 'mechanics_Singing',
 'mechanics_Solo / Solitaire Game',
 'mechanics_Spelling',
 'mechanics_Square Grid',
 'mechanics_Stacking and Balancing',
 'mechanics_Stock Holding',
 'mechanics_Storytelling',
 'mechanics_Sudden Death Ending',
 'mechanics_Take That',
 'mechanics_Team-Based Game',
 'mechanics_Tech Trees / Tech Tracks',
 'mechanics_Three Dimensional Movement',
 'mechanics_Tile Placement',
 'mechanics_Track Movement',
 'mechanics_Trading',
 'mechanics_Traitor Game',
 'mechanics_Trick-taking',
 'mechanics_Turn Order: Progressive',
 'mechanics_Turn Order: Time Track',
 'mechanics_Variable Phase Order',
 'mechanics_Variable Player Powers',
 'mechanics_Variable Set-up',
 'mechanics_Victory Points as a Resource',
 'mechanics_Voting',
 'mechanics_Worker Placement',
 'mechanics_Zone of Control']

In [1]:
from src.ml import BoardGameRecommender

recommender = BoardGameRecommender()
recommender.load_data()
recommendations = recommender.recommend('65')
# Now you'll see: id, name, final_score, cosine_similarity, etc.

In [2]:
recommendations

shape: (5, 8)
┌────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬───────────┐
│ id     ┆ name       ┆ final_scor ┆ cosine_sim ┆ normalized ┆ normalized ┆ normalized ┆ normalize │
│ ---    ┆ ---        ┆ e          ┆ ilarity    ┆ _year_simi ┆ _playing_t ┆ _bayesian_ ┆ d_popular │
│ str    ┆ str        ┆ ---        ┆ ---        ┆ larity     ┆ ime_simila ┆ rating     ┆ ity       │
│        ┆            ┆ f64        ┆ f64        ┆ ---        ┆ …          ┆ ---        ┆ ---       │
│        ┆            ┆            ┆            ┆ f64        ┆ ---        ┆ f64        ┆ f64       │
│        ┆            ┆            ┆            ┆            ┆ f64        ┆            ┆           │
╞════════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪═══════════╡
│ 2365   ┆ Sunset     ┆ 0.855426   ┆ 0.935414   ┆ 0.998018   ┆ 1.0        ┆ 0.5        ┆ 1.0       │
│        ┆ Blvd.      ┆            ┆            ┆            ┆            ┆            ┆           │
│ 10327  ┆ Linx       ┆ 0.845479   ┆ 0.935414   ┆ 0.996531   ┆ 1.0        ┆ 0.5        ┆ 0.951009  │
│ 3017   ┆ Framed!    ┆ 0.823726   ┆ 0.935414   ┆ 0.998018   ┆ 1.0        ┆ 0.5        ┆ 0.841499  │
│ 20236  ┆ Swim       ┆ 0.790873   ┆ 0.935414   ┆ 0.998018   ┆ 1.0        ┆ 0.5        ┆ 0.677233  │
│ 253612 ┆ アイドル発 ┆ 0.721573   ┆ 0.935414   ┆ 0.989098   ┆ 0.916667   ┆ 0.5        ┆ 0.397695  │
│        ┆ 掘！Digger ┆            ┆            ┆            ┆            ┆            ┆           │
│        ┆ s (Find    ┆            ┆            ┆            ┆            ┆            ┆           │
│        ┆ Idol! Dig… ┆            ┆            ┆            ┆            ┆            ┆           │
└────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴───────────┘

In [ ]:
recommendations.get

In [16]:
recommendations = recommender.recommend('13')

In [17]:
recommendations

shape: (5, 8)
┌────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬───────────┐
│ id     ┆ name       ┆ final_scor ┆ cosine_sim ┆ normalized ┆ normalized ┆ normalized ┆ normalize │
│ ---    ┆ ---        ┆ e          ┆ ilarity    ┆ _year_simi ┆ _playing_t ┆ _bayesian_ ┆ d_popular │
│ str    ┆ str        ┆ ---        ┆ ---        ┆ larity     ┆ ime_simila ┆ rating     ┆ ity       │
│        ┆            ┆ f64        ┆ f64        ┆ ---        ┆ …          ┆ ---        ┆ ---       │
│        ┆            ┆            ┆            ┆ f64        ┆ ---        ┆ f64        ┆ f64       │
│        ┆            ┆            ┆            ┆            ┆ f64        ┆            ┆           │
╞════════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪═══════════╡
│ 33562  ┆ De         ┆ 0.58943    ┆ 0.63901    ┆ 0.727273   ┆ 0.0        ┆ 0.5        ┆ 1.0       │
│        ┆ Kolonisten ┆            ┆            ┆            ┆            ┆            ┆           │
│        ┆ van Catan: ┆            ┆            ┆            ┆            ┆            ┆           │
│        ┆ Wegwe…     ┆            ┆            ┆            ┆            ┆            ┆           │
│ 265030 ┆ Catan: Big ┆ 0.542358   ┆ 0.653197   ┆ 0.477273   ┆ 0.0        ┆ 0.5        ┆ 0.86836   │
│        ┆ Box Jubile ┆            ┆            ┆            ┆            ┆            ┆           │
│        ┆ umeditie   ┆            ┆            ┆            ┆            ┆            ┆           │
│ 137594 ┆ Die        ┆ 0.448544   ┆ 0.632455   ┆ 0.659091   ┆ 0.0        ┆ 0.5        ┆ 0.339492  │
│        ┆ Siedler    ┆            ┆            ┆            ┆            ┆            ┆           │
│        ┆ von Catan: ┆            ┆            ┆            ┆            ┆            ┆           │
│        ┆ Das Min…   ┆            ┆            ┆            ┆            ┆            ┆           │
│ 179352 ┆ Raising    ┆ 0.428968   ┆ 0.666667   ┆ 0.545455   ┆ 0.0        ┆ 0.5        ┆ 0.247113  │
│        ┆ the Flags  ┆            ┆            ┆            ┆            ┆            ┆           │
│ 116555 ┆ Argentilan ┆ 0.424547   ┆ 0.547723   ┆ 0.636364   ┆ 0.0        ┆ 0.5        ┆ 0.357968  │
│        ┆ dia        ┆            ┆            ┆            ┆            ┆            ┆           │
└────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴───────────┘

In [7]:
recommender.get_radar_data(recommendations)

[{'game_id': '2365',
  'final_score': 0.8554261139882922,
  'scores': {'Similarity': 0.9354144334793091,
   'Year Match': 0.998017839444995,
   'Time Match': 1.0,
   'Rating': 0.5,
   'Popularity': 1.0}},
 {'game_id': '10327',
  'final_score': 0.8454791810532951,
  'scores': {'Similarity': 0.9354144334793091,
   'Year Match': 0.9965312190287413,
   'Time Match': 1.0,
   'Rating': 0.5,
   'Popularity': 0.9510086455331412}},
 {'game_id': '3017',
  'final_score': 0.8237258258038542,
  'scores': {'Similarity': 0.9354144334793091,
   'Year Match': 0.998017839444995,
   'Time Match': 1.0,
   'Rating': 0.5,
   'Popularity': 0.8414985590778099}},
 {'game_id': '20236',
  'final_score': 0.7908727998672548,
  'scores': {'Similarity': 0.9354144334793091,
   'Year Match': 0.998017839444995,
   'Time Match': 1.0,
   'Rating': 0.5,
   'Popularity': 0.6772334293948128}},
 {'game_id': '253612',
  'final_score': 0.7215730466376755,
  'scores': {'Similarity': 0.9354144334793091,
   'Year Match': 0.9890981169474727,
   'Time Match': 0.9166666666666666,
   'Rating': 0.5,
   'Popularity': 0.3976945244956773}}]